// project 2/react/src/App/App.js
import './App.css';
import React from 'react';
import TodoListElement from "./TodoListElement";
import axios from 'axios';

const App = () => {

	const endpoint = "http://localhost:3000/api";
	const [todos, setTodos] = React.useState([]);
	const [title, setTitle] = React.useState("");

	React.useEffect( () => {
		axios.get(endpoint).then(res => {setTodos(res.data)})
	}, []);

	const addNewTodo = async () =>{
		if(title.length === 0)return;
		const res = await axios.post(endpoint, {title: title}).then(res => res.data)
		setTodos([...todos,res]);
		setTitle("");
	}

	const deleteTodo = async (id) => {
		await axios.delete(`${endpoint}/${id}`);
		setTodos(todos.filter((todo) => todo.id !== id));
	}

	const toggleTodo = async (id) => {
		const el = todos.find(todo => todo.id === id);
		await axios.patch(`${endpoint}/${id}`,{title: el.title, done:!el.done});
		setTodos(todos.map(todo => todo.id === id? {...todo, done:!todo.done} : todo));
	}

  	return (
		<div className="App flex flex-col items-center w-full gap-6 px-4 pt-4">


			<div className="flex justify-center w-full p-4 bg-blue-500 rounded-md">
				<h1 className="flex items-center gap-8 text-5xl">nodeTODO react
					<span className="bg-blue-400 rounded-xl font-semibold size-[80px] flex justify-center place-items-center">
						{todos.filter(todo =>!todo.done).length}
					</span>
				</h1>
			</div>


			<div className="w-[600px] flex justify-center">
				<form className="flex gap-2">

					<input value={title} onChange={(e) => setTitle(e.target.value)}
					className="bg-transparent border-[2px] border-blue-500 rounded-md w-[530px] py-2 text-white text-center" type="text"/>

					<button onClick={addNewTodo} type='button'
					className="px-4 bg-blue-500 rounded-md">Add</button>

				</form>
			</div>


			<div className="w-[600px] pb-20">
				<ul className="flex flex-col gap-2">
					
					{todos.map((todoItem) => (
						<TodoListElement key={todoItem.id} todoItem={todoItem}  
						handleDelete={() => deleteTodo(todoItem.id)}
						handleToggle={() => toggleTodo(todoItem.id)} />
					))}

				</ul>            
			</div>


		</div>
  	);
}

export default App;

// project 2/angular/src/app/app.component.ts
import { CommonModule, NgFor } from '@angular/common';
import { Component, inject } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HttpClientModule, HttpClient } from  '@angular/common/http';

import {NgForm} from '@angular/forms';
import { FormsModule }   from '@angular/forms';


@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, NgFor, HttpClientModule,FormsModule,CommonModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})

export class AppComponent {

	title = 'notetodoA';
	todos:  {id: number, title: string, done: boolean}[] = [];

	get completedTodosCount(): number {
		return this.todos ? this.todos.filter(todo => todo.done === false).length : 0;
	}	

	httpClient = inject(HttpClient);
	ngOnInit() {
		this.httpClient.get('http://localhost:3000/api').subscribe((data: any) => {
			this.todos = data;
		});
	}

	onSubmit(f: NgForm) {
		if(f.valid){
			this.httpClient.post('http://localhost:3000/api', { title: f.value.title, done: false }).subscribe((data: any) => {
				this.todos.push(data);
			});			
			f.reset()
		}		
		
	}

	onToggle(id: number) {
		let targetid = this.todos.findIndex(todo => todo.id === id);
		this.httpClient.patch('http://localhost:3000/api/' + id, { title: this.todos[targetid].title, done: !this.todos[targetid].done }).subscribe((data: any) => {
			this.todos[targetid].done = !this.todos[targetid].done
		});
	}

	onDelete(id: number) {
		this.httpClient.delete('http://localhost:3000/api/' + id).subscribe((data: any) => {
			this.todos = this.todos.filter(todo => todo.id!== id);
		});
	}

}
<div class="flex flex-col items-center w-full gap-6 px-4 pt-4 text-white ">

  	<div class="flex justify-center w-full p-4 bg-red-600 rounded-md">
		<h1 class="flex items-center gap-8 text-5xl">nodeTODO angular
			<span class="bg-red-400 rounded-xl font-semibold size-[80px] flex justify-center place-items-center">
				{{ completedTodosCount }}
			</span>
		</h1>
  	</div>

	
	<div id="todo-form" class="w-[600px] flex justify-center">
		<form class="flex gap-2" #f="ngForm" (ngSubmit)="onSubmit(f)" novalidate>
			<input name="title" ngModel required #title="ngModel"
			 class="bg-transparent border-[2px] border-red-600 rounded-md w-[530px] py-2 text-white text-center" type="text">
			<button class="px-4 bg-red-600 rounded-md">Add</button>
		</form>
	</div>
	

	<div id="todos" class="w-[600px] pb-20">
		<ul class="flex flex-col gap-2">
			<li class="flex gap-2 cursor-pointer"
			*ngFor="let el of todos"  
			(click)="onToggle(el.id)">
				<span class="w-full min-h-[50px] p-3 bg-red-400 rounded-md font-medium overflow-x-auto"
				[ngClass]="{'opacity-20 line-through': el.done === true }">{{el.title}}</span>
				<button class="bg-red-600 rounded-md min-w-[50px] h-[50px] text-center font-bold" (click)="onDelete(el.id)">X</button>
			</li>
		</ul>
	</div>

	
</div>

<router-outlet />
